version: 2.1

orbs:
  github-maven-deploy: github-maven-deploy/github-maven-deploy@1.0.5
  circleci-maven-release-orb: sonatype-nexus-community/circleci-maven-release-orb@0.0.15

build-and-test: &build-and-test
  github-maven-deploy/build-and-test:
      mvn-build-test-command: mvn clean verify -PbuildKar -Dit
      mvn-collect-artifacts-command: |
        mkdir -p ~/project/artifacts/junit/
        find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/project/artifacts/junit/ \;
        cp ~/project/${rootArtifactId}-it/target/failsafe-reports/*.xml ~/project/artifacts/junit/

release-args: &release-args
  mvn-release-prepare-command: MAVEN_OPTS=-Xmx3072m mvn --batch-mode release:prepare -DscmCommentPrefix="[skip ci] [maven-release-plugin] " -PbuildKar -DskipTests
  ssh-fingerprints: "yo:ur:ss:hf:in:ge:rp:ri:nt:he:re..."
  context: rso-base
  filters:
    branches:
      only: master

workflows:
  build:
    jobs:
      - <<: *build-and-test

  run-release:
    jobs:
      - approve-release:
          type: approval
          filters:
            branches:
              only: master
      - circleci-maven-release-orb/run-maven-release:
          requires:
            - approve-release
          <<: *release-args

  release-from-master:
    jobs:
      - <<: *build-and-test
      - circleci-maven-release-orb/run-maven-release:
          requires:
            - github-maven-deploy/build-and-test
          <<: *release-args
